### ISSUE TITLE
Apply a11y linter to components

### ISSUE THREAD

**Issue by ianb** [FirefoxUX/photon-components-web#11]
We have some accessibility linting being developed at Mozilla, and could apply that to the components we have here. See https://github.com/mozilla-services/screenshots/pull/5004 for an example of how this is configured for CI.

Maybe simply applying this to the Storybook site would accomplish what we want. Ideally all the HTML examples we have (and indirectly the React components) should exemplify good a11y practice.

**Comment by kumar303** [comment]
On addons.mozilla.org we use eslint to catch a11y mistakes and it's nice because you don't have to be an a11y expert. The specific [set of rules](https://github.com/evcohen/eslint-plugin-jsx-a11y#readme) we use are meant for React but there is probably something similar for HTML. The advantage this has over the approach in the PR up above (which uses a browser) is that it would be faster. I don't know if it would cover the same things, though.
