### ISSUE TITLE
Set link hover/pressed state to blue 60/70

### ISSUE THREAD

**Issue by aminalhazwani** [FirefoxUX/photon-components-web#65]
It seems that the hover and pressed state of the link component https://firefoxux.github.io/photon-components-web/?selectedKind=Link&selectedStory=Everything&full=0&addons=1&stories=1&panelRight=0&addonPanel=lmorchard%2Fcodesample%2Fpanel different from what is specified here  https://design.firefox.com/photon/components/links.html#behaviors.

As a summary:

- Default state: Blue 60
- Hover state: Blue 60 + underline
- Pressed state: Blue 70 + underline

Two other things to consider:

- iirc we decided not to mark "external" links with an icon
- during our training with The Paciello Group their recommendation was to mark links with an underline style even in their default state.

Pinging @shorlander for confirmation on those two points.

**Comment by das-sein** [comment]
Hi Amin,

I'm looking to start contributing to this project. Should there also be a move to include :active <a> styling in line with the specification so that it looks like the following? Or are we sticking to just underlines?

![image](https://user-images.githubusercontent.com/6910190/52158292-d8f48780-2664-11e9-8290-9a4ad0b32b7a.png)
